name: docs
on:
  push:
    branches: ['main']
    tags: 'v*'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    container: tomeichlersmith/hps-env:latest
    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set Version
        run: |
          git config --global --add safe.directory $(pwd -P)
          _version_tag=$(git describe --tags)
          echo ${_version_tag}
          echo "release = '${_version_tag}'" >> docs/conf.py
      -
        name: Run Sphinx
        run: sphinx-build docs/ _site/
      -
        name: Upload Page Files
        uses: actions/upload-pages-artifact@v1
      -
        name: Publish to Website
        uses: actions/deploy-pages@v2

